### ISSUE TITLE
Undefined symbols: PIM_Plugin::webPageCreated(WebPage*)

### ISSUE THREAD

**Issue by ryandesign** [QupZilla/qupzilla#457]
QupZilla 1.3.0 fails to build on my OS X 10.6.8 system:

```
/usr/bin/g++-4.2 -arch x86_64 -headerpad_max_install_names -single_module -dynamiclib -o libPIM.dylib build/PIM_plugin.o build/PIM_handler.o build/PIM_settings.o build/moc_PIM_plugin.o build/moc_PIM_handler.o build/moc_PIM_settings.o build/qrc_PIM_res.o    -L/opt/local/var/macports/build/_Users_rschmidt_macports_dports_www_QupZilla/QupZilla/work/qupzilla-1.3.0/src/../bin -lQupZilla -L/opt/local/lib -lQtWebKit -lQtGui -lQtNetwork -lQtCore  
Undefined symbols:
  "PIM_Plugin::webPageCreated(WebPage*)", referenced from:
      PIM_Plugin::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)in moc_PIM_plugin.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
```
