### ISSUE TITLE
can not compile on haiku and QT 4.8

### ISSUE THREAD

**Issue by khallebal** [QupZilla/qupzilla#96]
hi 
thanks for the very promising young browser.
i tried to compile the source on haiku and QT 4.8,i keep getting the error msg about the "selectedHtml" was not declared in this scope in the webview.cpp.
is this a known issue,or is it only on haiku that it happens.
but it compiled on haiku with QT 4.7.3,where i got a similair error with "qtlocalpeer.cpp" after i added "# <include unistd> in the file.
thanks again
greetings
