### ISSUE TITLE
error: no member named 'FullScreen' in 'QKeySequence'

### ISSUE THREAD

**Issue by ryandesign** [QupZilla/qupzilla#1513]
QupZilla 1.8.4 fails to build on OS X 10.10 Yosemite:

```
app/mainmenu.cpp:632:52: error: no member named 'FullScreen' in 'QKeySequence'; did you mean 'isFullScreen'?
    m_actions[QSL("View/FullScreen")]->setShortcut(QKeySequence::FullScreen);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
                                                   isFullScreen
/opt/local/include/QtGui/qwidget.h:531:10: note: 'isFullScreen' declared here
    bool isFullScreen() const;
         ^
app/mainmenu.cpp:632:66: error: reference to non-static member function must be called; did you mean to call it with no arguments?
    m_actions[QSL("View/FullScreen")]->setShortcut(QKeySequence::FullScreen);
                                                   ~~~~~~~~~~~~~~^~~~~~~~~~
                                                                           ()
2 errors generated.
```
